AddMDisastersSpawn("Meteor", "md_disasters_meteor", "Disasters", true )
AddMDisastersSpawn("Volcano", "md_disasters_volcano", "Disasters", true )
AddMDisastersSpawn("Tornado", "md_disasters_tornado", "Disasters", true )
AddMDisastersSpawn("Earthquake", "md_disasters_earthquake", "Disasters", true )
AddMDisastersSpawn("Lighting Strike", "md_disasters_lightning_strike", "Disasters", true )
AddMDisastersSpawn("Lighting Storm", "md_weather_lightning_storm", "Weather", true )
AddMDisastersSpawn("Meteor Shower", "md_weather_meteor_shower", "Weather", true )
AddMDisastersSpawn("Rain", "md_weather_rain", "Weather", true )
AddMDisastersSpawn("Wind", "md_weather_wind", "Weather", true )
AddMDisastersSpawn("Lighting Storm With Rain", "md_weather_storm", "Weather", true )